---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
      annotations:
        "consul.hashicorp.com/connect-inject": "true"
        "consul.hashicorp.com/connect-service-upstreams": "backend:9091"
    spec:
      containers:
      - name: api
        image: nicholasjackson/fake-service:v0.7.7
        ports:
        - containerPort: 9090
        env:
        - name: "LISTEN_ADDR"
          value: "0.0.0.0:9090"
        - name: "NAME"
          value: "api service"
        - name: "MESSAGE"
          value: "api response"
        - name: "UPSTREAM_URIS"
          value: "http://localhost:9091"
        - name: "HTTP_CLIENT_KEEP_ALIVES"
          value: "false"
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090